apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
resources:
- ../../manifests/common/cert-manager/base
- ../..//manifests/common/cert-manager/kubeflow-issuer/base
- ../../manifests/common/istio-1-23/istio-crds/base
- ../../manifests/common/istio-1-23/istio-namespace/base
- ../../manifests/common/istio-1-23/istio-install/overlays/oauth2-proxy
- ../../manifests/common/oauth2-proxy/overlays/m2m-dex-and-kind
- ../../manifests/common/dex/overlays/oauth2-proxy